server:
  port: 9093
  max-http-header-size: 102400
#logging:
#  config: classpath:spring-logback.xml


#根据生产环境配置日志的输出路径(如果是linux,请新建个用户启动jar包)
innovation:
  #图片的保存路径
  file:
    #文件的根目录
    path: ${user.home}/competition

#spring datasource configuration
spring:
    datasource:
        name: mysql
        url:  "jdbc:mysql://localhost:3306/competition?characterEncoding=utf-8&useSSL=true"
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

        #druid configuration start
        #初始连接数
        initialSize: 3
        #最大数
        maxActive: 20
        #最小数
        minIdle: 3
        #等待超时最大时间,单位ms
        maxWait: 60000
        #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是ms
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间,单位是ms
        minEvictableIdleTimeMillis: 300000
        #申请连接时执行validationQuery检测连接是否有效.做了这个配置会降低性能
        testWhileIdle: true
        #归还连接时执行validationQuery检测连接是否有效,做了这个配置会降低性能
        testOnBorrow: false
        #并且保证安全性,申请连接的时候检测,如果空闲时间大于timeBetweenEvictionRunsMillis,执行validationQuery检测连接是否有效
        testOnReturn: false
        #打开PSCache,并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
        filters: stat,wall,log4j
        #通过connectProperties属性来打开mergeSql功能;慢SQL记录
        connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
        #合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true
    #file upload and download config
    http:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB



#mybatis-configuration
mybatis:
  mapper-locations: classpath:/mybatis/mapper/business/*.xml
  config-location: classpath:/config/mybatis-config.xml


#dozer mapping files location
dozer:
  mappingLocation: dozer/dozer-mappings.xml

#jasypt
jasypt:
  encryptor:
    password: f30bad03-997b-42d6-b791-be2762775c6b